{{- if .Values.bwsm_eso_provider.create_cluster_secret_store }}
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Release.Name }}-cluster-store
spec:
  provider:
    webhook:
      url: {{ include "bwsm-eso-provider.clusterSecretStore.secretUrl" . }}
      headers:
        Content-Type: application/json
      result:
        jsonPath: {{ include "bwsm-eso-provider.clusterSecretStore.secretJsonPath" . }}
{{- end }}
