{{- if not .Values.bwsm_eso_provider.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  BWS_ACCESS_TOKEN: {{ .Values.bwsm_eso_provider.auth.accessToken | b64enc | quote }}
{{- end }}
