{{- if and .Values.bwsm_eso_provider.create_cluster_secret_store .Values.bwsm_eso_provider.sample_secret.create }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.bwsm_eso_provider.sample_secret.secretName }}
  namespace: {{ .Release.Namespace }}
spec:
  target:
    name: {{ .Values.bwsm_eso_provider.sample_secret.secretName }}
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
      {{- include "bwsm-eso-provider.sampleSecret.data" . | nindent 2 }}

  data:
    - secretKey: {{ .Values.bwsm_eso_provider.sample_secret.secretKey }}
      sourceRef:
        storeRef:
          name: bwsm-cluster-store
          kind: ClusterSecretStore 
      remoteRef:
        key: {{ .Values.bwsm_eso_provider.sample_secret.remoteRef.key }}
        property: {{ .Values.bwsm_eso_provider.sample_secret.remoteRef.property }}
{{- end }}
