apiVersion: v1
kind: Service
metadata:
  name: {{ include "bwsm-eso-provider.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bwsm-eso-provider.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "bwsm-eso-provider.selectorLabels" . | nindent 4 }}
