include:
  - README.md
  - charts/**/README.md
  - chart-icon.png
  - artifacthub-repo.yml
  - index.yaml
exclude:
  - .github/
  - .gitattributes
  - .gitignore
  - .pre-commit-config.yaml
  - k8s-manifests/
  - src/
  - renovate.json
  - LICENSE
