---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bwsm-cluster-store
spec:
  provider:
    webhook:
      url: "http://bwsm-cli.bitwarden:8080/secret/{{ .remoteRef.key }}"
      headers:
        Content-Type: application/json
      result:
        jsonPath: "$.value"
