apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: example-secret-json
  namespace: bwsm
spec:
  target:
    name: example-secret-json
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        jsonDoc: |-
          {{ .jsonDoc }}
  data:
    - secretKey: jsonDoc
      sourceRef:
        storeRef:
          name: bwsm-cluster-store
          kind: ClusterSecretStore
      remoteRef:
        key: aaaabbbb-cccc-dddd-eeee-000011112222
        property: key
