name: Docker builds - manual and tagged

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Image Tag value"
        type: "string"
        required: true
  push:
    tags:        
      - '^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$'
      - '!bwsm-eso-provider-*'
    paths:
      - src/**

jobs:
  docker-image-build:
    environment: 'dockerhub'
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v3

      - name: Manual Build/Push
        if: ${{ github.event == 'workflow_dispatch' }}
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: |
            linux/amd64
          context: src
          tags: |
            bojanraic/bwsm-eso:${{ inputs.image_tag }}

      - name: Tagged Build/Push
        if: ${{ github.event != 'workflow_dispatch' }}
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: |
            linux/amd64
          context: src
          tags: |
            bojanraic/bwsm-eso:${{ github.ref_name }}
            bojanraic/bwsm-eso:latest
