name: Docker Nightly Builds

on:
  schedule:
    # 03.15 AM UTC
    - cron: '15 3 * * *'

jobs:
  docker-image-build:
    environment: 'dockerhub'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [amd64, arm64]    
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: ARM64 QEMU Setup
        if: matrix.platform == 'arm64'
        uses: docker/setup-qemu-action@v3

      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v3

      - name: Architecture specific Environment Variable Setup
        run: echo "BWS_DL_ARCH=$(if [ '${{ matrix.platform }}' == 'amd64' ]; then echo 'x86_64'; else echo 'aarch64'; fi)" >> $GITHUB_ENV

      - name: Nighhly Build/Push From Default Branch
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64, linux/arm64
          context: src
          build-args: |
            BWS_DL_ARCH=${{ env.BWS_DL_ARCH }}
          tags: |
            bojanraic/bwsm-eso:nightly

      - name: Most Recent Semver Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          semver_only: true
        id: most-recent-tag

      - name: Switch to Most Recent Tag
        if: steps.most-recent-tag.outputs.tag
        run: git checkout ${{ steps.most-recent-tag.outputs.tag }}

      - name: Scheduled Tag Build/Push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64, linux/arm64
          context: src
          build-args: |
            BWS_DL_ARCH=${{ env.BWS_DL_ARCH }}
          tags: |
            bojanraic/bwsm-eso:${{ steps.most-recent-tag.outputs.tag }}
            bojanraic/bwsm-eso:latest
