name: Docker Nightly Builds

on:
  workflow_dispatch:
  schedule:
    # 03.15 AM UTC
    - cron: '15 3 * * *'

jobs:
  docker-image-build:
    environment: 'dockerhub'
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Dockerhub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Docker Buildx Setup
        uses: docker/setup-buildx-action@v3

      - name: Nighhly Build/Push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: |
            linux/amd64
          context: src
          tags: |
            bojanraic/bwsm-eso:nightly

      - name: Most Recent Semver Tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          semver_only: true
        id: most-recent-tag

      - name: Switch to Most Recent Tag
        if: steps.most-recent-tag.outputs.tag
        run: git checkout ${{ steps.most-recent-tag.outputs.tag }}

      - name: Scheduled Tag Build/Push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: |
            linux/amd64
          context: src
          tags: |
            bojanraic/bwsm-eso:${{ steps.most-recent-tag.outputs.tag }}
